--EX 2:
--CONSULTA 1:
SELECT dt.nom 
FROM DATASETS D, EXPERIMENTS E
WHERE E.CONF = "2-0";

CREATE INDEX dataset_nom ON DATASETS (nom);

SELECT dt.nom 
FROM datasets dt WITH(INDEX(dataset_nom)), experiments ex
WHERE ex.conf="2-0";

--CONSULTA 2:
SELECT DISTINCT(V.CLASE)
FROM VECTOR V, DATASETS D
WHERE V.ID_DATASET = D.NOM and D.NOM = 'letter-recognition'
ORDER BY V.CLASE;

CREATE INDEX vector_clase ON vector (clase);

SELECT DISTINCT(v.clase)
FROM VECTOR V WITH(INDEX(VECTOR_CLASE)), DATASETS D
WHERE V.ID_DATASET = D.NOM and D.NOM = 'letter-recognition'
ORDER BY V.CLASE;

--CONSULTA 3:
SELECT DISTINCT(V.CLASE), D.NOM, count(V.ID_DATASET) AS TOTAL
FROM DATASETS D, VECTOR V
WHERE D.NOM = V.ID_DATASET
GROUP BY V.CLASE, D.NOM
ORDER BY D.NOM;

CREATE INDEX clase_iddataset ON vector (clase, id_dataset);

SELECT DISTINCT(V.CLASE), D.NOM, count(V.ID_DATASET) AS TOTAL
FROM DATASETS D, VECTOR V WITH(INDEX(clase_iddataset))
WHERE D.NOM = V.ID_DATASET
GROUP BY V.CLASE, D.NOM
ORDER BY D.NOM;

--CONSULTA 4:
SELECT MAX(TOTAL) AS MAX_CONF
FROM (SELECT E.CONF, COUNT(E.CONF) AS TOTAL	
FROM EXPERIMENTS E
WHERE E.METHOD = 'HOAD'
GROUP BY E.CONF);

CREATE INDEX experiments_index ON experiments (method, conf);

SELECT MAX(TOTAL) AS MAX_CONF
FROM (SELECT E.CONF, COUNT(E.CONF) AS TOTAL	
FROM EXPERIMENTS E WITH(INDEX(experiments_index))
WHERE E.METHOD = 'HOAD'
GROUP BY E.CONF);