--EX 1
--VISTA 1:
CREATE MATERIALIZED V1_MOSTRA
AS SELECT D.NOM, V.ID, V.VECTORVALUES, V.CLASE
FROM DATASETS D, VECTOR V
where V.ID_DATASETS = D.NOM
ORDER BY D.NOM;

--VISTA 2:
CREATE MATERIALIZED V2_MOSTRA AS
SELECT E.CONF, E.REPETICIO, E.METHOD, E.M, E.K E.SIGMA 
FROM EXPERIMENTS E

--VISTA 3:
CREATE MATERIALIZED V3_MOSTRA AS
SELECT D.NOM, E.CONFIGURATION, E.REPETICIO, E.ID, V.VECTORVALUES
FROM DATASETS D, EXPERIMENTS E, VECTOR V
WHERE E.ID = V.ID