
--DESCOMENTAR LINEA DE CONNECT PARA CONECTARSE CON EL USUARIO DESEADO

--CONNECT "AA_DETECTOR_OUTLIERS"/"12"
--CONNECT "AA_GESTOR_DADES"/"1234"
--CONNECT "AA_DESENVOLUPADOR"/"123456"
--CONNECT "AA_AUDITOR"/"12345678"

------------------------------------------------------------------------

--CREACION DE LA TABLA TEST
CREATE TABLE "Test"(
        camp1 varchar2(20),
        camp2 integer NOT NULL PRIMARY KEY
        );


--INSERCION DE VALORES 
INSERT INTO "Test"(camp1, camp2) VALUES ('Proba', 1);

--CONSULTA DE LA TABLA
SELECT * FROM "Test";

--BORAMOS CAMPO1
ALTER TABLE "Test"
DROP COLUMN camp1;

--AÑADIMOS NUEVO CAMPO
ALTER TABLE "Test" 
ADD camp3 VARCHAR(20) NULL;

--MODIFICAMOS EL TIPO DEL CAMPO AÑADIDO
ALTER TABLE "Test" 
MODIFY camp3 varchar2(200);

--CONSULTA DE LA TABLA ACTUALIZADA
SELECT * FROM "Test";

--BORRAMOS LA TABLA
DROP TABLE "Test";

