--ROLES--------------------------------------------------------------------------------------------------

--ROL_LOW:

CREATE ROLE "ROL_LOW";

GRANT SELECT ANY TABLE TO "ROL_LOW";

GRANT CREATE SESSION TO "ROL_LOW";


--ROL_MEDIUM:

CREATE ROLE "ROL_MEDIUM";
 
GRANT "ROL_LOW" TO "ROL_MEDIUM";

GRANT ALTER ANY INDEX TO "ROL_MEDIUM";
 
GRANT UPDATE ANY TABLE TO "ROL_MEDIUM";
 
GRANT INSERT ANY TABLE TO "ROL_MEDIUM";
 
GRANT COMMENT ANY TABLE TO "ROL_MEDIUM";
 
GRANT BACKUP ANY TABLE TO "ROL_MEDIUM";

GRANT ALTER ANY TABLE TO "ROL_MEDIUM";
 

--ROL_HIGH:

CREATE ROLE "ROL_HIGH";
 
GRANT "ROL_MEDIUM" TO "ROL_HIGH";
 
GRANT DROP ANY INDEX TO "ROL_HIGH";
 
GRANT CREATE ANY INDEX TO "ROL_HIGH";
 
GRANT DELETE ANY TABLE TO "ROL_HIGH";
 
GRANT DROP ANY TABLE TO "ROL_HIGH";
 
GRANT CREATE ANY TABLE TO "ROL_HIGH";
 
GRANT CREATE TABLE TO "ROL_HIGH";


--ROL_SUPER_CONNECTIONS_OBJECTS:

CREATE ROLE "ROL_SUPER_CONNECTIONS_OBJECTS";
 
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "ROL_SUPER_CONNECTIONS_OBJECTS";
  
GRANT CREATE SESSION TO "ROL_SUPER_CONNECTIONS_OBJECTS";
 
---------------------------------------------------------------------------------------------------------------------------------------------


--USERS--------------------------------------------------------------------------------------------------------------------------------------

--AA_DETECTOR_OUTLIERS (PASS: 12):

CREATE USER "AA_DETECTOR_OUTLIERS" IDENTIFIED BY VALUES 'S:0FD4B7CE58513466C4A1665D4A6CDC308C4F902100F63FE3CA58E75589B5;37D14B27EA823A1E'
      DEFAULT TABLESPACE "USERS"
      TEMPORARY TABLESPACE "TEMP";
      PROFILE "AA_DetectorOutlier"
 
	GRANT "ROL_LOW" TO "AA_DETECTOR_OUTLIERS";

 --AA_GESTOR_DADES (PASS: 1234):

 CREATE USER "AA_GESTOR_DADES" IDENTIFIED BY VALUES 'S:E893BADE47C97CAA66F4A2AB083A127A6EE2A0653EFBD499637C085420DD;71A1218A1E851F5E'
      DEFAULT TABLESPACE "USERS"
      TEMPORARY TABLESPACE "TEMP";
      PROFILE "AA_GestorDades"
 

   	GRANT "ROL_MEDIUM" TO "AA_GESTOR_DADES";

--AA_DESENVOLUPADOR (PASS: 123456):

CREATE USER "AA_DESENVOLUPADOR" IDENTIFIED BY VALUES 'S:CE01F0A97307494CDCD399E73CF4131A2B95C08E49F1F17D875BC0018DAB;0EE647D3988449B9'
      DEFAULT TABLESPACE "USERS"
      TEMPORARY TABLESPACE "TEMP";
      PROFILE "AA_Desenvolupador"
 

   	GRANT "ROL_HIGH" TO "AA_DESENVOLUPADOR";

--AA_AUDITOR (PASS: 12345678):

CREATE USER "AA_AUDITOR" IDENTIFIED BY VALUES 'S:CBADEFABCC48B6549A43888A2FBA832545639DEA8DDAA627073CC6A751FE;62D503C8834E4B6D'
     DEFAULT TABLESPACE "USERS"
     TEMPORARY TABLESPACE "TEMP";
     PROFILE "AA_Auditior"
 
 	GRANT "ROL_SUPER_CONNECTIONS_OBJECTS" TO "AA_AUDITOR";

---------------------------------------------------------------------------------------------------------------------------------------------

--------------------------PROFILES-----------------------------------------------------------------------------------------------------------

CREATE PROFILE "AA_DetectorOutlier"
LIMIT
    COMPOSITE_LIMIT DEFAULT
    SESSIONS_PER_USER 5
    CPU_PER_SESSION 10000
    CPU_PER_CALL 1
    LOGICAL_READS_PER_SESSION DEFAULT
    LOGICAL_READS_PER_CALL DEFAULT
    IDLE_TIME 30
    CONNECT_TIME UNLIMITED
    PRIVATE_SGA 20971520
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_REUSE_TIME 12
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION NULL
    PASSWORD_LOCK_TIME DEFAULT
    PASSWORD_GRACE_TIME;


CREATE PROFILE "AA_GestorDades"
LIMIT
    COMPOSITE_LIMIT DEFAULT
    SESSIONS_PER_USER 4
    CPU_PER_SESSION 10000
    CPU_PER_CALL 1
    LOGICAL_READS_PER_SESSION DEFAULT
    LOGICAL_READS_PER_CALL DEFAULT
    IDLE_TIME 30
    CONNECT_TIME UNLIMITED
    PRIVATE_SGA 20971520
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_TIME 12
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION NULL
    PASSWORD_LOCK_TIME DEFAULT
    PASSWORD_GRACE_TIME 2;


CREATE PROFILE "AA_Desenvolupador"
LIMIT
    COMPOSITE_LIMIT DEFAULT
    SESSIONS_PER_USER 1
    CPU_PER_SESSION 10000
    CPU_PER_CALL 1
    LOGICAL_READS_PER_SESSION DEFAULT
    LOGICAL_READS_PER_CALL DEFAULT
    IDLE_TIME 30
    CONNECT_TIME UNLIMITED
    PRIVATE_SGA 20971520
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 180
    PASSWORD_REUSE_TIME 12
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION NULL
    PASSWORD_LOCK_TIME DEFAULT
    PASSWORD_GRACE_TIME 2;


CREATE PROFILE "AA_Auditior"
LIMIT
    COMPOSITE_LIMIT DEFAULT
    SESSIONS_PER_USER 1
    CPU_PER_SESSION 10000
    CPU_PER_CALL 1
    LOGICAL_READS_PER_SESSION DEFAULT
    LOGICAL_READS_PER_CALL DEFAULT
    IDLE_TIME 30
    CONNECT_TIME UNLIMITED
    PRIVATE_SGA 20971520
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 180
    PASSWORD_REUSE_TIME 12
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION NULL
    PASSWORD_LOCK_TIME DEFAULT
    PASSWORD_GRACE_TIME 2

----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------