--DESCOMENTAR LINEA DE CONNECT PARA CONECTARSE CON EL USUARIO DESEADO

--CONNECT "AA_DETECTOR_OUTLIERS"/"12";
CONNECT "AA_GESTOR_DADES"/"1234"
--CONNECT "AA_DESENVOLUPADOR"/"123456"
--CONNECT "AA_AUDITOR"/"12345678"

------------------------------------------------------------------------

SELECT * FROM USER_ROLE_PRIVS;
SELECT * FROM ROLE_SYS_PRIVS;
--DESC DBA_USERS;
SELECT * FROM USER_USERS;