#SERVER CONFIGURATION
SERVER_NAME="localhost"
PORT=27017

#SERVER CREATION OPTIONS
DATABASE_NAME="VECTORES_UCI"
COLLECTIONS_NAMES=['PRUEBA_1','PRUEBA_2','VECTORS']
COLLECTIONS_NAMES_X=['DATABASES_INFO','RESULTS','SET_UP_EXPERIMENTS','METHODS','EXPERIMENTS','VECTORS']
COLLECTIONS_OPEN=[{"TEST": "TEST" },{"TEST": "TEST" }]

#DATA_LOCATION_CONFIGURATION
VECTOR_PATH="../UCI/"
VECTOR_FILENAMES_DATA=['breast-cancer-wisconsin.data.txt','ionosphere.data.txt','iris.data.txt',
                        'letter-recognition.txt']
                        
VECTOR_FILENAMES_NAMES=['breast-cancer-wisconsin.names.txt','ionosphere.names.txt','letter-recognition.names']

METHOD_PATH='../METHODS_DATA/'
METHOD_FILENAME_NAMES='methods.names.txt'
METHOD_FILENAME_DATA='methods.txt'

#DATA_INSERTION_CONFIGURATION
INSERT_DATA=True
INSERT_NAMES=True
#NUM_TUPLES_TO_INSERT=10
VERBOSE=False

